#!/bin/bash

echo "------ HOOK START - BUILD -------"
# printenv
# https://docs.docker.com/docker-cloud/builds/advanced/
docker build --build-arg GITHUB_TOKEN=$TOKEN -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
